### ISSUE TITLE
Cellranger version 3

### ISSUE THREAD

**Issue by ashrosewood** [hb-gitified/cellrangerRkit#1]
Do you plan on bumping your version for cellranger version 3 since functions such `load_cellranger_matrix` does not work with the latest versions output?

**Comment by HenrikBengtsson** [comment]
First, please note that I'm neither a 10x affiliate nor a cellrangerRkit maintainer.  This repos is just archiving what 10x provides.

Looking at https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit, it looks like they stopped maintaining cellrangerRkit.  Have you found one elsewhere?

**Comment by ashrosewood** [comment]
I did see they dropped it on the third party packages list. I was just curious if there was a plan to update cellrangerRkit to version 3, or if I should just transition my scripts to Seurat now, which I will go ahead and do. Thanks for getting back to me.
